src/Entity/Ecole.php
<?php

namespace App\Entity;

use App\Repository\EcoleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: EcoleRepository::class)]
#[UniqueEntity("nom_ecole")]
class Ecole
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_ecole;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\ManyToOne(targetEntity: NiveauEtude::class, inversedBy: 'ecoles')]
    #[ORM\JoinColumn(nullable: false)]
    private $niveau_etude;

    #[ORM\OneToMany(mappedBy: 'ecole', targetEntity: Eleve::class, orphanRemoval: true)]
    private $eleves;

    public function __construct()
    {
        $this->eleves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEcole(): ?string
    {
        return $this->nom_ecole;
    }

    public function setNomEcole(string $nom_ecole): self
    {
        $this->nom_ecole = $nom_ecole;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getNiveauEtude(): ?NiveauEtude
    {
        return $this->niveau_etude;
    }

    public function setNiveauEtude(?NiveauEtude $niveau_etude): self
    {
        $this->niveau_etude = $niveau_etude;

        return $this;
    }

    /**
     * @return Collection<int, Eleve>
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addElefe(Eleve $elefe): self
    {
        if (!$this->eleves->contains($elefe)) {
            $this->eleves[] = $elefe;
            $elefe->setEcole($this);
        }

        return $this;
    }

    public function removeElefe(Eleve $elefe): self
    {
        if ($this->eleves->removeElement($elefe)) {
            // set the owning side to null (unless already changed)
            if ($elefe->getEcole() === $this) {
                $elefe->setEcole(null);
            }
        }

        return $this;
    }
}

src/Entity/NiveauEtude.php
<?php

namespace App\Entity;

use App\Repository\NiveauEtudeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NiveauEtudeRepository::class)]
class NiveauEtude
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_niveau_etude;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\OneToMany(mappedBy: 'niveau_etude', targetEntity: Ecole::class, orphanRemoval: true)]
    private $ecoles;

    #[ORM\OneToMany(mappedBy: 'niveau_etude', targetEntity: Classe::class, orphanRemoval: true)]
    private $classes;

    public function __construct()
    {
        $this->ecoles = new ArrayCollection();
        $this->classes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomNiveauEtude(): ?string
    {
        return $this->nom_niveau_etude;
    }

    public function setNomNiveauEtude(string $nom_niveau_etude): self
    {
        $this->nom_niveau_etude = $nom_niveau_etude;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Ecole>
     */
    public function getEcoles(): Collection
    {
        return $this->ecoles;
    }

    public function addEcole(Ecole $ecole): self
    {
        if (!$this->ecoles->contains($ecole)) {
            $this->ecoles[] = $ecole;
            $ecole->setNiveauEtude($this);
        }

        return $this;
    }

    public function removeEcole(Ecole $ecole): self
    {
        if ($this->ecoles->removeElement($ecole)) {
            // set the owning side to null (unless already changed)
            if ($ecole->getNiveauEtude() === $this) {
                $ecole->setNiveauEtude(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Classe>
     */
    public function getClasses(): Collection
    {
        return $this->classes;
    }

    public function addClass(Classe $class): self
    {
        if (!$this->classes->contains($class)) {
            $this->classes[] = $class;
            $class->setNiveauEtude($this);
        }

        return $this;
    }

    public function removeClass(Classe $class): self
    {
        if ($this->classes->removeElement($class)) {
            // set the owning side to null (unless already changed)
            if ($class->getNiveauEtude() === $this) {
                $class->setNiveauEtude(null);
            }
        }

        return $this;
    }
}

src/Form/NiveauEtudeType.php
<?php

namespace App\Form;

use App\Entity\NiveauEtude;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NiveauEtudeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_niveau_etude')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => NiveauEtude::class,
        ]);
    }
}

src/Controller/NiveauEtudeController.php
<?php

namespace App\Controller;

use App\Entity\Ecole;
use App\Entity\Classe;
use App\Entity\NiveauEtude;
use App\Form\NiveauEtudeType;
use App\Form\NiveauEtudeEcoleType;
use App\Form\NiveauEtudeClasseType;
use App\Repository\EcoleRepository;
use App\Repository\ClasseRepository;
use App\Repository\NiveauEtudeRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/niveauetude')]
class NiveauEtudeController extends AbstractController
{
    #[Route('/', name: 'app_niveau_etude_index', methods: ['GET'])]
    public function index(NiveauEtudeRepository $niveauEtudeRepository): Response
    {
        return $this->render('niveau_etude/index.html.twig', [
            'niveau_etudes' => $niveauEtudeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_niveau_etude_new', methods: ['GET', 'POST'])]
    public function new(Request $request, NiveauEtudeRepository $niveauEtudeRepository): Response
    {
        $niveauEtude = new NiveauEtude();
        $form = $this->createForm(NiveauEtudeType::class, $niveauEtude);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $niveauEtude->setUpdatedAt(new \DateTimeImmutable());
            $niveauEtude->setCreatedAt(new \DateTimeImmutable());
            $niveauEtudeRepository->add($niveauEtude);
            return $this->redirectToRoute('app_niveau_etude_show', ['id'=>$niveauEtude->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('niveau_etude/new.html.twig', [
            'niveau_etude' => $niveauEtude,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_niveau_etude_show', methods: ['GET'])]
    public function show(NiveauEtude $niveauEtude): Response
    {
        return $this->render('niveau_etude/show.html.twig', [
            'niveau_etude' => $niveauEtude,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_niveau_etude_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, NiveauEtude $niveauEtude, NiveauEtudeRepository $niveauEtudeRepository): Response
    {
        $form = $this->createForm(NiveauEtudeType::class, $niveauEtude);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $niveauEtude->setUpdatedAt(new \DateTimeImmutable());
            $niveauEtudeRepository->add($niveauEtude);
            return $this->redirectToRoute('app_niveau_etude_show', ['id'=>$niveauEtude->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('niveau_etude/edit.html.twig', [
            'niveau_etude' => $niveauEtude,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_niveau_etude_delete', methods: ['POST'])]
    public function delete(Request $request, NiveauEtude $niveauEtude, NiveauEtudeRepository $niveauEtudeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$niveauEtude->getId(), $request->request->get('_token'))) {
            $niveauEtudeRepository->remove($niveauEtude);
            return $this->redirectToRoute('app_niveau_etude_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('niveau_etude/delete.html.twig',[
            'niveau_etude'=>$niveauEtude,
        ]);
        
    }
    #[Route('/{id}/listeecole', name: 'app_niveau_etude_liste_ecole', methods: ['GET'])]
    public function listeecole(NiveauEtude $niveau_etude): Response
    {
        $ecoles=$niveau_etude->getEcoles();
        return $this->render('niveau_etude/listeecole.html.twig', [
            'ecoles'=>$ecoles,
            'niveau_etude'=>$niveau_etude
        ]);
    }

    #[Route('/{id}/newecole', name: 'app_niveau_etude_new_ecole', methods: ['GET', 'POST'])]
    public function newecole(Request $request, NiveauEtude $niveau_etude, EcoleRepository $ecoleRepository): Response
    {
        $ecole=new Ecole();
        $form = $this->createForm(NiveauEtudeEcoleType::class, $ecole);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $ecole->setUpdatedAt(new \DateTimeImmutable());
            $ecole->setCreatedAt(new \DateTimeImmutable());
            $ecole->setNiveauEtude($niveau_etude);
            $ecoleRepository->add($ecole);
            return $this->redirectToRoute('app_niveau_etude_liste_ecole', ['id'=>$niveau_etude->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('niveau_etude/newecole.html.twig', [
            'niveau_etude' => $niveau_etude,
            'ecole'=>$ecole,
            'form' => $form,
        ]);
    }

}

templates/niveau_etude/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Niveau Etude | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Niveau Etude</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_niveau_etude_show', {'id':niveau_etude.id}) }}" title="Accueil Niveau Etude" ><i class="fas fa-fw fa-home"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <p class="text-muted font-13 m-b-30">
                    Suppression Niveau Etude
                  </p>
                  <div class="card">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-5 col-xs-12 mr-2">
                          <div class="card o-hidden border-0 shadow-lg my-5">
                            <div class="card-body p-1">
                              <div class="row">
                                <div class="col-lg-10 mx-auto">
                                  <div class="p-5">
                                    <p>Supprimer  <strong> {{niveau_etude.NomNiveauEtude}} </strong></p>
                                    <form method="post" action="{{ path('app_niveau_etude_delete', {'id': niveau_etude.id}) }}" onsubmit="return confirm(Êtes-vous sûr de vouloir effectuer cette action ?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ niveau_etude.id) }}">
                                        <button class="btn btn-danger">Delete <i class="fas fa-trash-alt"></i></button>
                                    </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/niveau_etude/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Niveau Etude | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Niveau Etude</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_niveau_etude_show', {'id':niveau_etude.id}) }}" title="Accueil Niveau Etude" ><i class="fas fa-fw fa-home"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <p class="text-muted font-13 m-b-30">
                    Modification Niveau Etude
                  </p>
                  <div class="card">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-5 col-xs-12 mr-2">
                          <div class="card o-hidden border-0 shadow-lg my-5">
                            <div class="card-body p-1">
                              <div class="row">
                                <div class="col-lg-10 mx-auto">
                                    <div class="p-5">
                                        {{form_start(form, {'attr':{'class':'form'}})}}
                                            <div class="form-floating mb-3">
                                                {{form_row(form.nom_niveau_etude, {'attr':{'class':"form-control", 'placeholder':"Niveau Etude", 'required':"required", 'autofocus':"autofocus"}})}}
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-warning">Modifier <i class="fas fa-edit"></i> </button>
                                            </div>
                                        {{ form_end(form) }}
                                    </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/niveau_etude/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Niveau Etude | {{ parent() }}{% endblock %}

{% block body %}

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Niveau Etude</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_niveau_etude_new') }}" title="Ajout Niveau d'Etude" ><i class="fas fa-fw fa-plus-circle"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                    <p class="text-muted font-13 m-b-30">
                      La liste des niveaux d'etude existant à mboth.
                    </p>
                    <table id="datatable-buttons" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th class="text-center">Id</th>
                                <th class="text-center">Nom Niveau</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for niveau_etude in niveau_etudes %}
                            <tr>
                                <td class="text-center">{{ niveau_etude.id }}</td>
                                <td class="text-center">{{ niveau_etude.nomNiveauEtude }}</td>
                                <td class="text-center">
                                    <a href="{{ path('app_niveau_etude_show', {'id': niveau_etude.id}) }}"><i class="fas fa-eye text-info"></i></a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td class="text-center" colspan="5">no records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/niveau_etude/listeecole.html.twig
{% extends 'base.html.twig' %}

{% block title %}Niveau Etude | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Niveau Etude</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_niveau_etude_new_ecole', {'id':niveau_etude.id}) }}" title="Ajout Maison" ><i class="fas fa-fw fa-plus-circle"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                    <p class="text-muted font-13 m-b-30">
                      La liste des écoles de niveau {{ niveau_etude.nomNiveauEtude }}.
                    </p>
                    <table id="datatable-buttons" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th class="text-center">Id</th>
                            <th class="text-center">Ecole</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for ecole in ecoles %}
                        <tr>
                            <td class="text-center">{{ ecole.id }}</td>
                            <td class="text-center">{{ ecole.nomEcole }}</td>
                            <td class="text-center">
                                <a href="{{ path('app_ecole_show', {'id': ecole.id}) }}"><i class="fas fa-eye text-info"></i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="4">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/niveau_etude/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Niveau Etude | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Niveau d'Etude</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_niveau_etude_index')}}" title="Accueil Niveau Etude" ><i class="fas fa-fw fa-home"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <p class="text-muted font-13 m-b-30">
                    Ajout Niveau Etude
                  </p>
                  <div class="card">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-5 col-xs-12 mr-2">
                          <div class="card o-hidden border-0 shadow-lg my-5">
                            <div class="card-body p-1">
                              <div class="row">
                                <div class="col-lg-10 mx-auto">
                                    <div class="p-3">
                                        {{form_start(form, {'attr':{'class':'form'}})}}
                                            <div class="form-floating mb-3">
                                                {{form_row(form.nom_niveau_etude, {'attr':{'class':"form-control", 'placeholder':"Niveau Etude", 'required':"required", 'autofocus':"autofocus"}})}}
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-success">Valider <i class="fas fa-save"></i> </button>
                                            </div>
                                        {{ form_end(form) }}
                                    </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/niveau_etude/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Niveau Etude | {{ parent() }}{% endblock %}

{% block body %}
<div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Niveau Etude</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a class="collapse-link" href="{{ path('app_niveau_etude_liste_ecole', {'id':niveau_etude.id}) }}" class="text-decoration-none float-left m-1" title="Liste Ecole"><i class="fas fa-list text-info"></i> </a> 
                </li>
                <li>
                    <a class="collapse-link" href="{{ path('app_niveau_etude_delete', {'id': niveau_etude.id}) }}" class="text-decoration-none float-left m-1" title="Supprimer"> <i class="fas fa-trash-alt text-danger"></i> </a>
                </li>
                <li>
                    <a class="collapse-link" href="{{ path('app_niveau_etude_edit', {'id': niveau_etude.id}) }}"  class="text-decoration-none float-left m-1" title="Modifier"> <i class="fas fa-edit text-warning"></i> </a>
                </li>
                <li>
                    <a class="collapse-link" href="{{ path('app_niveau_etude_index') }}" class="text-decoration-none float-left m-1" title="Accueil"><i class="fas fa-home text-primary"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box table-responsive">
                        <p class="text-muted font-13 m-b-30">
                          Niveau d'Etude {{ niveau_etude.nomNiveauEtude}}.
                        </p>
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-5 col-xs-12 mr-2">
                                        <div class="card o-hidden border-0 shadow-lg my-5">
                                            <div class="card-body p-1">
                                                <div class="row">
                                                    <div class="col-lg-10 col-xs-12 mx-auto">
                                                        <div class="p-1">
                                                            <ul class="list-group">
                                                                <li class="list-group-item">
                                                                    <p><strong>Id</strong>: {{ niveau_etude.id }}</p>
                                                                </li>
                                                                <li class="list-group-item">
                                                                    <p><strong>Niveau Etude</strong>: {{ niveau_etude.NomNiveauEtude }}</p>
                                                                </li>
                                                            </ul>                            
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}