src/Entity/Maison.php
<?php

namespace App\Entity;

use App\Repository\MaisonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: MaisonRepository::class)]
#[UniqueEntity("nom_maison")]

class Maison
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_maison;

    #[ORM\Column(type: 'string', length: 255)]
    private $code_maison;

    #[ORM\ManyToOne(targetEntity: Secteur::class, inversedBy: 'maisons')]
    #[ORM\JoinColumn(nullable: false)]
    private $secteur;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\OneToMany(mappedBy: 'maison', targetEntity: Personne::class, orphanRemoval: true)]
    private $personnes;

    #[ORM\Column(type: 'text')]
    private $localisation;

    #[ORM\Column(type: 'boolean')]
    private $existence_arbre;

    #[ORM\OneToMany(mappedBy: 'maison', targetEntity: Arbre::class)]
    private $arbres;

    #[ORM\Column(type: 'boolean')]
    private $existence_eau;

    #[ORM\Column(type: 'boolean')]
    private $existence_electricite;

    #[ORM\Column(type: 'boolean')]
    private $existence_internet;

    #[ORM\Column(type: 'boolean')]
    private $existence_fosse_septique;

    #[ORM\Column(type: 'text')]
    private $qr_maison;

    public function __construct()
    {
        $this->arbres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomMaison(): ?string
    {
        return $this->nom_maison;
    }

    public function setNomMaison(string $nom_maison): self
    {
        $this->nom_maison = $nom_maison;

        return $this;
    }

    public function getCodeMaison(): ?string
    {
        return $this->code_maison;
    }

    public function setCodeMaison(string $code_maison): self
    {
        $this->code_maison = $code_maison;

        return $this;
    }

    public function getSecteur(): ?Secteur
    {
        return $this->secteur;
    }

    public function setSecteur(?Secteur $secteur): self
    {
        $this->secteur = $secteur;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Personne>
     */
    public function getPersonnes(): Collection
    {
        return $this->personnes;
    }

    public function addPersonne(Personne $personne): self
    {
        if (!$this->personnes->contains($personne)) {
            $this->personnes[] = $personne;
            $personne->setMaison($this);
        }

        return $this;
    }

    public function removePersonne(Personne $personne): self
    {
        if ($this->personnes->removeElement($personne)) {
            // set the owning side to null (unless already changed)
            if ($personne->getMaison() === $this) {
                $personne->setMaison(null);
            }
        }

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(string $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }

    public function isExistenceArbre(): ?bool
    {
        return $this->existence_arbre;
    }

    public function setExistenceArbre(bool $existence_arbre): self
    {
        $this->existence_arbre = $existence_arbre;

        return $this;
    }

    /**
     * @return Collection<int, Arbre>
     */
    public function getArbres(): Collection
    {
        return $this->arbres;
    }

    public function addArbre(Arbre $arbre): self
    {
        if (!$this->arbres->contains($arbre)) {
            $this->arbres[] = $arbre;
            $arbre->setMaison($this);
        }

        return $this;
    }

    public function removeArbre(Arbre $arbre): self
    {
        if ($this->arbres->removeElement($arbre)) {
            // set the owning side to null (unless already changed)
            if ($arbre->getMaison() === $this) {
                $arbre->setMaison(null);
            }
        }

        return $this;
    }

    public function isExistenceEau(): ?bool
    {
        return $this->existence_eau;
    }

    public function setExistenceEau(bool $existence_eau): self
    {
        $this->existence_eau = $existence_eau;

        return $this;
    }

    public function isExistenceElectricite(): ?bool
    {
        return $this->existence_electricite;
    }

    public function setExistenceElectricite(bool $existence_electricite): self
    {
        $this->existence_electricite = $existence_electricite;

        return $this;
    }

    public function isExistenceInternet(): ?bool
    {
        return $this->existence_internet;
    }

    public function setExistenceInternet(bool $existence_internet): self
    {
        $this->existence_internet = $existence_internet;

        return $this;
    }

    public function isExistenceFosseSeptique(): ?bool
    {
        return $this->existence_fosse_septique;
    }

    public function setExistenceFosseSeptique(bool $existence_fosse_septique): self
    {
        $this->existence_fosse_septique = $existence_fosse_septique;

        return $this;
    }

    public function getQrMaison(): ?string
    {
        return $this->qr_maison;
    }

    public function setQrMaison(string $qr_maison): self
    {
        $this->qr_maison = $qr_maison;

        return $this;
    }


}

src/Entity/Personne.php
<?php

namespace App\Entity;

use App\Repository\PersonneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PersonneRepository::class)]
class Personne
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'date')]
    private $date_naissance;

    #[ORM\Column(type: 'string', length: 255)]
    private $lieu_naissance;

    #[ORM\Column(type: 'string', length: 255)]
    private $sexe;

    #[ORM\Column(type: 'string', length: 255)]
    private $situation_matrimoniale;

    #[ORM\ManyToOne(targetEntity: Maison::class, inversedBy: 'personnes')]
    #[ORM\JoinColumn(nullable: false)]
    private $maison;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\OneToMany(mappedBy: 'personne', targetEntity: User::class, orphanRemoval: true)]
    private $users;

    #[ORM\OneToMany(mappedBy: 'personne', targetEntity: Eleve::class, orphanRemoval: true)]
    private $eleves;

    #[ORM\Column(type: 'boolean')]
    private $existence_maladie;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->eleves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): self
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getSituationMatrimoniale(): ?string
    {
        return $this->situation_matrimoniale;
    }

    public function setSituationMatrimoniale(string $situation_matrimoniale): self
    {
        $this->situation_matrimoniale = $situation_matrimoniale;

        return $this;
    }

    public function getMaison(): ?Maison
    {
        return $this->maison;
    }

    public function setMaison(?Maison $maison): self
    {
        $this->maison = $maison;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setPersonne($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getPersonne() === $this) {
                $user->setPersonne(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Eleve>
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addElefe(Eleve $elefe): self
    {
        if (!$this->eleves->contains($elefe)) {
            $this->eleves[] = $elefe;
            $elefe->setPersonne($this);
        }

        return $this;
    }

    public function removeElefe(Eleve $elefe): self
    {
        if ($this->eleves->removeElement($elefe)) {
            // set the owning side to null (unless already changed)
            if ($elefe->getPersonne() === $this) {
                $elefe->setPersonne(null);
            }
        }

        return $this;
    }

    public function isExistenceMaladie(): ?bool
    {
        return $this->existence_maladie;
    }

    public function setExistenceMaladie(bool $existence_maladie): self
    {
        $this->existence_maladie = $existence_maladie;

        return $this;
    }
}

src/Controller/SecteurController.php
<?php

namespace App\Controller;

use App\Entity\Maison;
use App\Entity\Secteur;
use App\Form\SecteurType;
use App\Service\QrCodeService;
use App\Form\SecteurMaisonType;
use App\Repository\MaisonRepository;
use App\Repository\SecteurRepository;
use App\Repository\PersonneRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/secteur')]
class SecteurController extends AbstractController
{
    #[Route('/', name: 'app_secteur_index', methods: ['GET'])]
    public function index(SecteurRepository $secteurRepository): Response
    {
        return $this->render('secteur/index.html.twig', [
            'secteurs' => $secteurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_secteur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SecteurRepository $secteurRepository): Response
    {
        $secteur = new Secteur();
        $form = $this->createForm(SecteurType::class, $secteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $secteur->setUpdatedAt(new \DateTimeImmutable());
            $secteur->setCreatedAt(new \DateTimeImmutable());
            $secteurRepository->add($secteur);
            return $this->redirectToRoute('app_secteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('secteur/new.html.twig', [
            'secteur' => $secteur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_secteur_show', methods: ['GET'])]
    public function show(Secteur $secteur): Response
    {
        return $this->render('secteur/show.html.twig', [
            'secteur' => $secteur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_secteur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Secteur $secteur, SecteurRepository $secteurRepository): Response
    {
        $form = $this->createForm(SecteurType::class, $secteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $secteur->setUpdatedAt(new \DateTimeImmutable());
            $secteurRepository->add($secteur);
            return $this->redirectToRoute('app_secteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('secteur/edit.html.twig', [
            'secteur' => $secteur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_secteur_delete', methods: ['POST'])]
    public function delete(Request $request, Secteur $secteur, SecteurRepository $secteurRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$secteur->getId(), $request->request->get('_token'))) {
            $secteurRepository->remove($secteur);

            return $this->redirectToRoute('app_secteur_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('cellule/delete.html.twig',[
            'secteur'=>$secteur
        ]);    
    }
    #[Route('/{id}/listemaison', name: 'app_secteur_liste_maison', methods: ['GET'])]
    public function listemaison(Secteur $secteur): Response
    {
        $maisons=$secteur->getMaisons();
        return $this->render('secteur/listemaison.html.twig', [
            'maisons'=>$maisons,
            'secteur'=>$secteur
        ]);
    }

    #[Route('/{id}/newmaison', name: 'app_secteur_new_maison', methods: ['GET', 'POST'])]
    public function newmaison(Request $request, Secteur $secteur, MaisonRepository $maisonRepository, QrCodeService $qrcodeservice): Response
    {
        $maison=new Maison();  
        $qr_code=null;
        $form = $this->createForm(SecteurMaisonType::class, $maison);
        $form->handleRequest($request);
        $code_maison="";
        if ($form->isSubmitted() && $form->isValid()) {            
            $mysecteur=strtoupper(substr($secteur->getNomSecteur(),0,3));
            $cellule= $secteur->getCellule()->getNomCellule();
            $quartier= $secteur->getCellule()->getQuartier()->getNomQuartier();
            $house=$quartier." ".$cellule;
            $code_maison= implode('', array_map(function($p) { return strtoupper($p[0]); }, explode(' ', $house)));
            $code=strtoupper(substr($code_maison.''.$mysecteur.''.md5(random_int(0,9999)),0,10));
            $maison->setQrMaison((string)$qr_code);
            $maison->setUpdatedAt(new \DateTimeImmutable());
            $maison->setCreatedAt(new \DateTimeImmutable());
            $maison->setCodeMaison($code);
            $maison->setSecteur($secteur);
            $maisonRepository->add($maison);            
            $qr_code=$qrcodeservice->qrcode($maison->getId().'/codevalidationmaison',$maison->getId());
            $maison->setQrMaison((string)$qr_code);
            $maisonRepository->add($maison);   
            return $this->redirectToRoute('app_secteur_liste_maison', ['id'=>$secteur->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('secteur/newmaison.html.twig', [
            'maison' => $maison,
            'secteur'=>$secteur,
            'form' => $form,
        ]);
    }

    
    #[Route("/{id}/education",name:"app_secteur_education", methods: ['GET'])]
    public function education(Secteur $secteur)
    {
        $maisons=$secteur->getMaisons();

        return $this->render('secteur/education.html.twig',[
            'maisons'=>$maisons,
            'secteur'=>$secteur
        ]);
    }
    #[Route("/{id}/listepersonnes",name:"app_secteur_personnes", methods: ['GET'])]
    public function societe(Secteur $secteur)
    {
        $maisons=$secteur->getMaisons();

        return $this->render('secteur/listepersonne.html.twig',[
            'maisons'=>$maisons,
            'secteur'=>$secteur
        ]);
    }
    
}

templates/secteur/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Secteur | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Quartier</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_secteur_show', {'id':secteur.id}) }}" title="Accueil Secteur" ><i class="fas fa-fw fa-home"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <p class="text-muted font-13 m-b-30">
                    Suppression Secteur
                  </p>
                  <div class="card">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-5 col-xs-12 mr-2">
                          <div class="card o-hidden border-0 shadow-lg my-5">
                            <div class="card-body p-1">
                              <div class="row">
                                <div class="col-lg-10 mx-auto">
                                  <div class="p-5">
                                    <p>
                                        Supprimer  <strong> {{secteur.NomSecteur}} </strong>
                                    </p>                            
                                    <form method="post" action="{{ path('app_secteur_delete', {'id': secteur.id}) }}" onsubmit="return confirm(Êtes-vous sûr de vouloir effectuer cette action ?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ secteur.id) }}">
                                        <button class="btn btn-danger">Supprimer <i class="fas fa-trash-alt"></i></button>
                                    </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/secteur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Secteur | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Secteur</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_secteur_show', {'id':secteur.id}) }}" title="Accueil Secteur" ><i class="fas fa-fw fa-home"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <p class="text-muted font-13 m-b-30">
                    Modification Secteur
                  </p>
                  <div class="card">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-5 col-xs-12 mr-2">
                          <div class="card o-hidden border-0 shadow-lg my-5">
                            <div class="card-body p-1">
                              <div class="row">
                                <div class="col-lg-10 mx-auto">
                                  <div class="p-5">
                                    {{form_start(form, {'attr':{'class':'form'}})}}
                                        <div class="form-floating mb-3">
                                            {{form_row(form.nom_secteur, {'attr':{'class':"form-control", 'placeholder':"Secteur", 'required':"required", 'autofocus':"autofocus"}})}}
                                        </div>
                                        <div class="form-floating mb-3">
                                            {{form_row(form.cellule, {'attr':{'class':"form-control js-example-basic-single", 'placeholder':"Cellule", 'required':"required", 'autofocus':"autofocus"}})}}
                                        </div>
                                        <div class="form-floating mb-3">
                                            {{form_row(form.localisation, {'attr':{'class':"form-control", 'placeholder':"Localisation"}})}}
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success">Modifier <i class="fas fa-edit"></i></button>
                                        </div>
                                    {{ form_end(form) }}
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/secteur/listemaison.html.twig
{% extends 'base.html.twig' %}

{% block title %}Maison | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Secteur</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a href="{{path('app_secteur_show', {'id':secteur.id})}}" class="collapse-link"><i class="fa fa-home"></i></a>  
                </li>
                <li>
                    <a  href="{{ path('app_secteur_new_maison', {'id':secteur.id}) }}" title="Ajout Maison" ><i class="fas fa-fw fa-plus-circle"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <p class="text-muted font-13 m-b-30">
                    La liste des maisons du secteur {{ secteur.NomSecteur}}.
                  </p>
                  <table id="datatable-buttons" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th class="text-center">Id</th>
                            <th class="text-center">Maison</th>
                            <th class="text-center">Code maison</th>
                            <th class="text-center">Secteur</th>
                            <th class="text-center">Code QR</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for maison in maisons %}
                        <tr>
                            <td class="text-center">{{ maison.id }}</td>
                            <td class="text-center">{{ maison.nomMaison }}</td>
                            <td class="text-center">{{ maison.codeMaison }}</td>
                            <td class="text-center">{{ maison.secteur.NomSecteur }}</td>
                            <td class="text-center"><a href="{{ path('app_maison_show_code', {'id': maison.id}) }}"><i class="fas fa-qrcode text-success"></i></a></td>
                            <td class="text-center">
                                <a href="{{ path('app_maison_show', {'id': maison.id}) }}"><i class="fas fa-eye text-info"></i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="6">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/secteur/listepersonne.html.twig
{% extends 'base.html.twig' %}

{% block title %}Secteur | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Secteur</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a href="{{path('app_secteur_show', {'id':secteur.id})}}" class="collapse-link"><i class="fa fa-home"></i></a>  
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <p class="text-muted font-13 m-b-30">
                    Population du secteur {{ secteur.NomSecteur}}.
                  </p>
                  <table id="datatable-buttons" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th class="text-center">Id</th>
                            <th class="text-center">Prenom</th>
                            <th class="text-center">Nom</th>
                            <th class="text-center">Date et Lieu de Naissance</th>
                            <th class="text-center">Sexe</th>
                            <th class="text-center">Maison</th>
                            <th class="text-center">Situation matrimoniale</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for maison in maisons %}
                        {% for personne in maison.personnes %}
                            <tr>
                                <td class="text-center">{{ personne.id }}</td>
                                <td class="text-center">{{ personne.prenom }}</td>
                                <td class="text-center">{{ personne.nom }}</td>
                                <td class="text-center">{{ personne.dateNaissance ? personne.dateNaissance|date('Y-m-d') : '' }} à {{ personne.lieuNaissance }}</td>
                                <td class="text-center">{{ personne.sexe }}</td>
                                <td class="text-center">{{ personne.maison.NomMaison }}</td>
                                <td class="text-center">{{ personne.situationMatrimoniale }}</td>
                                <td class="text-center">
                                    <a href="{{ path('app_personne_show', {'id':personne.id}) }}"><i class="fas fa-eye text-info"></i></a>
                                </td>
                            </tr>
                        {% else %}
                        <tr>
                            <td colspan="10">no records found</td>
                        </tr>
                            
                        {% endfor %}
                    {% endfor %}
                    </tbody>
                </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}