src/Entity/Personne.php
<?php

namespace App\Entity;

use App\Repository\PersonneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PersonneRepository::class)]
class Personne
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'date')]
    private $date_naissance;

    #[ORM\Column(type: 'string', length: 255)]
    private $lieu_naissance;

    #[ORM\Column(type: 'string', length: 255)]
    private $sexe;

    #[ORM\Column(type: 'string', length: 255)]
    private $situation_matrimoniale;

    #[ORM\ManyToOne(targetEntity: Maison::class, inversedBy: 'personnes')]
    #[ORM\JoinColumn(nullable: false)]
    private $maison;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\OneToMany(mappedBy: 'personne', targetEntity: User::class, orphanRemoval: true)]
    private $users;

    #[ORM\OneToMany(mappedBy: 'personne', targetEntity: Eleve::class, orphanRemoval: true)]
    private $eleves;

    #[ORM\Column(type: 'boolean')]
    private $existence_maladie;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->eleves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): self
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getSituationMatrimoniale(): ?string
    {
        return $this->situation_matrimoniale;
    }

    public function setSituationMatrimoniale(string $situation_matrimoniale): self
    {
        $this->situation_matrimoniale = $situation_matrimoniale;

        return $this;
    }

    public function getMaison(): ?Maison
    {
        return $this->maison;
    }

    public function setMaison(?Maison $maison): self
    {
        $this->maison = $maison;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setPersonne($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getPersonne() === $this) {
                $user->setPersonne(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Eleve>
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addElefe(Eleve $elefe): self
    {
        if (!$this->eleves->contains($elefe)) {
            $this->eleves[] = $elefe;
            $elefe->setPersonne($this);
        }

        return $this;
    }

    public function removeElefe(Eleve $elefe): self
    {
        if ($this->eleves->removeElement($elefe)) {
            // set the owning side to null (unless already changed)
            if ($elefe->getPersonne() === $this) {
                $elefe->setPersonne(null);
            }
        }

        return $this;
    }

    public function isExistenceMaladie(): ?bool
    {
        return $this->existence_maladie;
    }

    public function setExistenceMaladie(bool $existence_maladie): self
    {
        $this->existence_maladie = $existence_maladie;

        return $this;
    }
}

src/Entity/Quartier.php
<?php

namespace App\Entity;

use App\Repository\QuartierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: QuartierRepository::class)]
#[UniqueEntity("nom_quartier")]
class Quartier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_quartier;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\OneToMany(mappedBy: 'quartier', targetEntity: Cellule::class, orphanRemoval: true)]
    private $cellules;

    #[ORM\Column(type: 'text')]
    private $localisation;

    public function __construct()
    {
        $this->cellules = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomQuartier(): ?string
    {
        return $this->nom_quartier;
    }

    public function setNomQuartier(string $nom_quartier): self
    {
        $this->nom_quartier = $nom_quartier;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Cellule>
     */
    public function getCellules(): Collection
    {
        return $this->cellules;
    }

    public function addCellule(Cellule $cellule): self
    {
        if (!$this->cellules->contains($cellule)) {
            $this->cellules[] = $cellule;
            $cellule->setQuartier($this);
        }

        return $this;
    }

    public function removeCellule(Cellule $cellule): self
    {
        if ($this->cellules->removeElement($cellule)) {
            // set the owning side to null (unless already changed)
            if ($cellule->getQuartier() === $this) {
                $cellule->setQuartier(null);
            }
        }

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(string $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }
}

src/Form/QuartierType.php
<?php

namespace App\Form;

use App\Entity\Quartier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class QuartierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_quartier', TextType::class, [
                'label'=>false
            ])
            ->add('localisation', TextareaType::class, [
                'attr'=> [
                    'class'=>'tinymce'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Quartier::class,
        ]);
    }
}

src/Controller/QuartierController.php
<?php

namespace App\Controller;

use App\Entity\Cellule;
use App\Entity\Quartier;
use App\Form\QuartierType;
use App\Form\QuartierCelluleType;
use App\Repository\CelluleRepository;
use App\Repository\QuartierRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/quartier')]
class QuartierController extends AbstractController
{
    #[Route('/', name: 'app_quartier_index', methods: ['GET'])]
    public function index(QuartierRepository $quartierRepository): Response
    {
        return $this->render('quartier/index.html.twig', [
            'quartiers' => $quartierRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_quartier_new', methods: ['GET', 'POST'])]
    public function new(Request $request, QuartierRepository $quartierRepository): Response
    {
        $quartier = new Quartier();
        $form = $this->createForm(QuartierType::class, $quartier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quartier->setUpdatedAt(new \DateTimeImmutable());
            $quartier->setCreatedAt(new \DateTimeImmutable());
            $quartierRepository->add($quartier);
            return $this->redirectToRoute('app_quartier_show', ['id'=>$quartier->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quartier/new.html.twig', [
            'quartier' => $quartier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_quartier_show', methods: ['GET'])]
    public function show(Quartier $quartier): Response
    {
        return $this->render('quartier/show.html.twig', [
            'quartier' => $quartier,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_quartier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Quartier $quartier, QuartierRepository $quartierRepository): Response
    {
        $form = $this->createForm(QuartierType::class, $quartier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quartier->setUpdatedAt(new \DateTimeImmutable());
            $quartierRepository->add($quartier);
            return $this->redirectToRoute('app_quartier_show', ['id'=>$quartier->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quartier/edit.html.twig', [
            'quartier' => $quartier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_quartier_delete', methods: ['GET','POST'])]
    public function delete(Request $request, Quartier $quartier, QuartierRepository $quartierRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$quartier->getId(), $request->request->get('_token'))) {
            $quartierRepository->remove($quartier);        
            return $this->redirectToRoute('app_quartier_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('quartier/delete.html.twig', [
            'quartier' => $quartier
        ]);
    }

    #[Route('/{id}/listequartier', name: 'app_quartier_liste_cellule', methods: ['GET'])]
    public function listecellule(Quartier $quartier): Response
    {
        $cellules=$quartier->getCellules();
        return $this->render('quartier/listecellule.html.twig', [
            'cellules'=>$cellules,
            'quartier'=>$quartier
        ]);
    }

    #[Route('/{id}/newcellule', name: 'app_quartier_new_cellule', methods: ['GET', 'POST'])]
    public function new_personne(Request $request, Quartier $quartier, CelluleRepository $celluleRepository): Response
    {
        $cellule=new Cellule();
        $form = $this->createForm(QuartierCelluleType::class, $cellule);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $cellule->setUpdatedAt(new \DateTimeImmutable());
            $cellule->setCreatedAt(new \DateTimeImmutable());
            $cellule->setQuartier($quartier);
            $celluleRepository->add($cellule);
            return $this->redirectToRoute('app_quartier_liste_cellule', ['id'=>$quartier->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('quartier/newcellule.html.twig', [
            'quartier' => $quartier,
            'cellule'=>$cellule,
            'form' => $form,
        ]);
    }

    
    
    #[Route("/{id}/education",name:"app_quartier_education", methods: ['GET'])]
    public function education(Quartier $quartier)
    {
        return $this->render('quartier/education.html.twig',[
            'quartier'=>$quartier
        ]);
    }
    #[Route("/{id}/listepersonnes",name:"app_quartier_personne", methods: ['GET'])]
    public function societe(Quartier $quartier)
    {
        return $this->render('quartier/listepersonne.html.twig',[
            'quartier'=>$quartier
        ]);
    }
}

templates/quartier/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quartier | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Quartier</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_quartier_show', {'id':quartier.id}) }}" title="Accueil Quartier" ><i class="fas fa-fw fa-home"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <p class="text-muted font-13 m-b-30">
                    Suppression Quartier
                  </p>
                  <div class="card">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-5 col-xs-12 mr-2">
                          <div class="card o-hidden border-0 shadow-lg my-5">
                            <div class="card-body p-1">
                              <div class="row">
                                <div class="col-lg-10 mx-auto">
                                  <div class="p-5">
                                    <p>Supprimer le quartier <strong class="text-danger">{{ quartier.NomQuartier }}</strong>  ?</p>
                                    <form method="post" action="{{ path('app_quartier_delete', {'id': quartier.id}) }}" onsubmit="return confirm(Êtes-vous sûr de vouloir effectuer cette action ?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quartier.id) }}">
                                        <button class="btn btn-danger">Delete <i class="fas fa-trash-alt"></i></button>
                                    </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/quartier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quartier | {{ parent() }}{% endblock %}

{% block body %}
<div class="row">
  <div class="col-md-12 col-sm-12 ">
    <div class="x_panel">
      <div class="x_title">
        <h2>Quartier</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li>
              <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li>
              <a href="{{ path('app_quartier_show', {'id':quartier.id}) }}" title="Accueil Quartier" ><i class="fas fa-fw fa-home"></i></a>
          </li>
          <li>
              <a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="row">
          <div class="col-sm-12">
            <div class="card-box table-responsive">
              <p class="text-muted font-13 m-b-30">
                Modification Quartier
              </p>
              <div class="card">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-5 col-xs-12 mr-2">
                      <div class="card o-hidden border-0 shadow-lg my-5">
                        <div class="card-body p-1">
                          <div class="row">
                            <div class="col-lg-10 mx-auto">
                              <div class="p-5">
                                {{form_start(form, {'attr':{'class':'form'}})}}
                                    <div class="form-floating mb-3">
                                        {{form_row(form.nom_quartier, {'attr':{'class':"form-control", 'placeholder':"Quartier", 'required':"required", 'autofocus':"autofocus"}})}}
                                    </div>
                                        <div class="form-floating mb-3">
                                            {{form_row(form.localisation, {'attr':{'class':"form-control", 'placeholder':"Localisation"}})}}
                                        </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-warning">Modifier <i class="fas fa-edit"></i></button>
                                    </div>
                                {{ form_end(form) }}
                                </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/quartier/education.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quartier | {{ parent() }}{% endblock %}

{% block body %}

    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Quartier</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_quartier_show', {'id':quartier.id}) }}" title="Accueil Quartier" ><i class="fas fa-fw fa-home"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                    <p class="text-muted font-13 m-b-30">
                        <strong class="text-primary">Education</strong> / Liste des élèves du Quartier {{ quartier.NomQuartier}}.
                    </p>
                    <table  id="datatable-buttons" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th class="text-center">Id</th>
                                <th class="text-center">Nom Complet</th>
                                <th class="text-center">Adresse</th>
                                <th class="text-center">Ecole</th>
                                <th class="text-center">Classe</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for cellule in quartier.cellules %}
                            {% for secteur in cellule.secteurs %}
                                {% for maison in secteur.maisons %}
                                    {% for personne in maison.personnes %}
                                        {% for eleve in personne.eleves %}
                                            <tr>
                                                <td class="text-center">{{ eleve.id }}</td>
                                                <td class="text-center">{{ eleve.personne.prenom }} {{ eleve.personne.nom }}</td>
                                                <td class="text-center">{{ eleve.personne.maison.secteur.NomSecteur }}/{{eleve.personne.maison.secteur.cellule.NomCellule}}</td>
                                                <td class="text-center">{{eleve.ecole.NomEcole}}</td>
                                                <td class="text-center">{{eleve.classe.NomClasse}}</td>
                                                <td class="text-center">
                                                    <a href="{{ path('app_eleve_show', {'id':eleve.id}) }}"><i class="fas fa-eye text-info"></i></a>
                                                </td>
                                            </tr>
                                        {% endfor %}                            
                                    {% endfor %}
                                {% endfor %}
                            {% endfor %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/quartier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quartier | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Quartier</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li>
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li>
                  <a href="{{ path('app_quartier_new') }}" title="Ajout Quartier" ><i class="fas fa-fw fa-plus-circle"></i></a>
              </li>
              <li>
                  <a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                  <p class="text-muted font-13 m-b-30">
                    La liste des quartiers existant à Mboth et l'ensemble des informations.
                  </p>
                  <table id="datatable-buttons" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th class="text-center">Id</th>
                            <th class="text-center">Quartier</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for quartier in quartiers %}
                        <tr>
                            <td class="text-center">{{ quartier.id }}</td>
                            <td class="text-center">{{ quartier.nomQuartier }}</td>
                            <td class="text-center">
                                <a href="{{ path('app_quartier_show', {'id': quartier.id}) }}"><i class="fas fa-eye text-info" title="Détails"></i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td class="text-center" colspan="5">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/quartier/listepersonne.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quartier | {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>Quartier</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a href="{{ path('app_quartier_show', {'id':quartier.id})}}" class="collapse-link"><i class="fas fa-home"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                    <p class="text-muted font-13 m-b-30">
                      Population du quartier {{ quartier.NomQuartier}}.
                    </p>
                    <table id="datatable-buttons" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th class="text-center">Id</th>
                                <th class="text-center">Prenom</th>
                                <th class="text-center">Nom</th>
                                <th class="text-center">Date et Lieu de Naissance</th>
                                <th class="text-center">Sexe</th>
                                <th class="text-center">Maison</th>
                                <th class="text-center">Situation matrimoniale</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for cellule in quartier.cellules %}
                            {% for secteur in cellule.secteurs %}
                                {% for maison in secteur.maisons %}
                                    {% for personne in maison.personnes %}
                                        <tr>
                                            <td class="text-center">{{ personne.id }}</td>
                                            <td class="text-center">{{ personne.prenom }}</td>
                                            <td class="text-center">{{ personne.nom }}</td>
                                            <td class="text-center">{{ personne.dateNaissance ? personne.dateNaissance|date('Y-m-d') : '' }} à {{ personne.lieuNaissance }}</td>
                                            <td class="text-center">{{ personne.sexe }}</td>
                                            <td class="text-center">{{ personne.maison.NomMaison }}</td>
                                            <td class="text-center">{{ personne.situationMatrimoniale }}</td>
                                        </tr>                                    
                                    {% endfor %}

                                {% endfor %}                            
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="10">no records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}